import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

//Almost all boiler plate code
export const api = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: import.meta.env.VITE_BASE_URL}),
    reducerPath: "main",
    tagTypes: ["Kpis"],
    endpoints: (build) => ({
        getKpis: build.query<void, void>({
            //I make a url call to the VITE_BASE_URL/kpi/kpis
            query: () => "kpi/kpis/",
            providesTags: ["Kpis"]
        })
    })
})

export const { useGetKpisQuery } = api;
//useGetKpisQuery is autogenerated by adding "use" and "query" to getKpis